version: '3'
services:
    firefox:
        image: selenium/standalone-firefox:latest

    driverapi:
        build: ./driverapi
        image: driverapi:test
        volumes:
            - ./driverapi:/app
        depends_on:
            - firefox
        links:
            - firefox
            